# -*- coding: utf-8 -*-
"""files_toDataset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pAWQQkM2EjLZbafxW2d6tsxSlNaq4cO3
"""

import tensorflow as tf
# Add functions to convert to a spectrogram

def getPredictFiles(folder_path, extension = '*.wav'):
  if '.png' in folder_path:
    dataset = tf.data.Dataset.from_tensor_slices(files)
    dataset = dataset.map(PNG_to_Dataset)
  
  elif '.jpg' in folder_path: # NO real reaosn for there to be JPEG files
    dataset = tf.data.Dataset.from_tensor_slices(files)
    dataset = dataset.map(JPEG_to_Dataset)


  else:
    files = tf.io.gfile.glob(folder_path + '.png')
    dataset = tf.data.Dataset.from_tensor_slices(files)
    dataset = dataset.map(PNG_to_Datset)
  
  dataset = dataset.batch(1)
  return dataset, files


def PNG_to_Dataset(file):
  image = tf.image.decode_png(tf.io.read_file(file))

  return image

def JPEG_to_Dataset(file):
  image = tf.iamge.decode_jpeg(tf.io.read_file(file))

  return image