# -*- coding: utf-8 -*-
"""progressCallback.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ouwON96H7dwVi04hI-oWeQgITIXUnUaQ
"""

import tensorflow as tf
from PIL import Image
from tensorflow import keras
import numpy as np
import os
class CheckProgressCallback(keras.callbacks.Callback):

  def __init__(self,freq = 5):
    super(CheckProgressCallback, self).__init__()
    self.freq = 5
  
  def on_epoch_end(self, epoch, logs = None):
    if epoch % self.freq == 0:
      prediction = self.model.predict(self.progress_dataset)
      for i in range(np.shape(prediction)[0]):
        im = Image.fromarray((prediction[i] * 255).astype(np.uint8))
        filename = self.progress_files[i][self.progress_files[i].rfind('/')+1:self.progress_files[i].rfind('.')]+'_{}_pred.png'.format(epoch)
        im.save(os.path.join(self.progress_save_folder,filename))
      print('Wrote Progress Images')